import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { EB_Garamond } from "next/font/google";
import Footer from "@/components/Footer";
import ToastProvider from "@/providers/ToastProvider";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "QueensHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={ebGaramond.className}
      >
        <ToastProvider/>
         <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
